#ifndef __useDirectShow_namespace_include_hpp
#define __useDirectShow_namespace_include_hpp

//注意：改这个头文件命名空间声明结构的时候，一定要下面这一行宏定义的值，这个宏定义本身不能和其它宏定义重复，这个宏定义的值要和实际命名空间匹配
#define ____aRottenGeneralNameThisX_thisNamespace_thisUse_randomMacro_201812201701_nidfopbjpsnbdsinbpeirn aRottenGeneralNameThisX_thisNamespace::useDirectShow
namespace aRottenGeneralNameThisX_thisNamespace
{
	namespace useDirectShow
	{

	}

}

#endif
